module.exports = {
  rules: {
    // "adjacent-overload-signatures"
    // "array-type":
    // "class-name"
    // "curly"
    // "deprecation"- warning
    // "forin"
    // "indent"
    // "label-position"
    // "linebreak-style"
    // "member-ordering"
    // "new-parens"
    // "no-arg"
    // "no-bitwise"
    // "no-conditional-assignment"
    // "no-consecutive-blank-lines"
    // "no-console"
    // "no-construct"
    // "no-debugger"
    // "no-duplicate-super"
    // "no-duplicate-variable"
    // "no-eval"
    // "no-invalid-template-strings"
    // "no-invalid-this"
    // "no-mergeable-namespace"
    // "no-namespace"
    // "no-reference"
    // "no-reference-import"
    // "no-sparse-arrays"
    // "no-switch-case-fall-through"
    // "no-trailing-whitespace"
    // "no-unsafe-finally"
    // "no-unused-expression"
    // "no-var-keyword"
    // "no-void-expression"
    // "object-literal-sort-keys"
    // "one-line"
    // "one-variable-per-declaration"
    // "ordered-imports" - warning
    // "prefer-template"- warning
    // "quotemark"
    // "radix"
    // "return-undefined"
    // "semicolon"
    // "switch-default"
    // "trailing-comma"
    // "triple-equals"
    // "typedef"
    // "use-isnan"
    // "variable-name"
  }
};
